name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-dir: dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        id: build
        env:
          CI: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: list file
        run: ls

      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          # SOURCE:  .
          TARGET: ${{ secrets.PATH }}